# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshrinked',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='urlshrinked',
            name='tmstamp',
        ),
    ]
